### ISSUE TITLE
rel.String should be NVARCHAR

### ISSUE THREAD

**Issue by billgraziano** [go-rel/mssql#6]
Disclaimer: I'm just reviewing the code while deciding whether to use or not.  I haven't used this for real yet.

I believe a GO string (Unicode) best matches to NVARCHAR instead of VARCHAR.  That will support the full Unicode set.  At least that's what I've done in my code and it's worked well.

https://github.com/go-rel/mssql/blob/e7d7d121f21fde19a9e6d66c8a9f946631b9d868/mssql.go#L137-L142

**Comment by Fs02** [comment]
Thank you again for this great feedback, I've created a pr to address this issue.
please take a look if you have time 😄 

FYI: This column mapping is only used for migration functionality and it's also possible to explicitly define corresponding MSSQL type using the following function:

```go
func (t *Table) Column(name string, typ ColumnType, options ...ColumnOption)
```

this issue gave me an idea to create extension type on this driver, to better cover all available types in MSSQL, thanks
