### ISSUE TITLE
rel.Text should be NVARCHAR(MAX)

### ISSUE THREAD

**Issue by billgraziano** [go-rel/mssql#7]
Same disclaimer:  Just reviewing code, not an actual user at this point.

The "text" type is deprecated in SQL Server and will be removed in a future version.

https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15 

Microsoft suggests replacing with NVACHAR(MAX) or VARCHAR(MAX).  I'd prefer NVARCHAR(MAX) to support Unicode.

https://github.com/go-rel/mssql/blob/e7d7d121f21fde19a9e6d66c8a9f946631b9d868/mssql.go#L143-L145

**Comment by Fs02** [comment]
Thanks for your feedback, it's very helpful 🙏 
I've created a pr to address this issue, please take a look if you have time 😄
