### ISSUE TITLE
Timestamp is deprecated

### ISSUE THREAD

**Issue by billgraziano** [go-rel/mssql#8]
Disclaimer: Just reviewing code at this point.

https://github.com/go-rel/mssql/blob/e7d7d121f21fde19a9e6d66c8a9f946631b9d868/mssql.go#L143-L145

The "timestamp" keyword for a data type is deprecated and will be removed in a future version.  They suggest using "rowversion".

https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver15#remarks

**Comment by Fs02** [comment]
hi, thanks for your feedback again 😄 

hmm, in that case `timestamp`/`rowversion` has a totally different meaning compared to other database.

it seems different database have different definition for timestamp, probably better to drop this type from `rel` package and let the driver defines it in the driver package? 🤔

**Comment by billgraziano** [comment]
I don't know enough about the other databases to know how they handle this.  I'm just glad you're thinking about it :-)
