### ISSUE TITLE
Consider rel.BigID

### ISSUE THREAD

**Issue by billgraziano** [go-rel/mssql#9]
Disclaimer: Just reviewing code at this point.

`rel.ID` is interesting.  It mixes in a few different things.  It would be interesting to have a `rel.BigID` that maps to `BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY`

I'm using BIGINT instead of INT in more and more tables these days -- especially for anything transactional.

**Comment by Fs02** [comment]
Hi, thanks again for taking your time for reviewing this code 😄 

I'm totally agree with this one, in my previous company, we've also moved some of the table to bigint.

**Comment by Fs02** [comment]
Thanks for the suggestion, `BigID` now available https://github.com/go-rel/mssql/pull/11
